# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('descripcion', models.TextField(max_length=50)),
                ('slug', models.SlugField()),
                ('create_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
